Update readme
imsweb/x12-parser pull request #46
Opened 2021-02-11 14:59 UTC by angelaszek

2021-02-17 14:02 UTC, ctmay4 requested changes
Overall looks really good.  I made a few suggestions.  

It's interesting that in seeing this I would make some changes to the library API to make things simpler.  Maybe in the future.

2021-02-17 14:02 UTC, ctmay4 commented on README.md
> +X12Reader reader = new X12Reader(FileType.ANSI837_5010_X222, new File(url.getFile()));
I'd prefer to not use `this.getClass().getResource()`.  The constructor takes a `File` so can you just say:

```java
X12Reader reader = new X12Reader(FileType.ANSI837_5010_X222, new File("/path/file.txt"));
```

2021-02-23 20:02 UTC, angelaszek commented
Thanks for taking a look. I implemented the edits.

2021-02-23 20:32 UTC, ctmay4 approved these changes

2021-02-23 20:32 UTC, merged